### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Lafil** [ITLec/ITLec.CRMChartGuy.XRMToolBox.AdvancedChartEditor#2]
[TG01-Top 10 Companies.txt](https://github.com/ITLec/ITLec.CRMChartGuy.XRMToolBox.AdvancedChartEditor/files/1080945/TG01-Top.10.Companies.txt)

I am getting an error on one of my custom case entity based charts. See attached XML.
It runs off case entity’s OOB attributes so you should be ok to import it if you need to.
The plugin gives an error when trying to go to the Chart / Series / Series / CustomProperties node.
“Object reference not set to an instance of an object”.

See attached chart. It runs off case entity’s OOB attributes so you should be ok to import it into test environnement if you need to.

**Comment by ITLec** [comment]
Hello, 

Kindly test the uploaded dll ["V2.0 - ITLecChartGuy.AdvancedChartEditor" in your onedrive folder"].
Please confirm that "This issue has been solved".

Thanks,
Rasheed

**Comment by Lafil** [comment]
Hi Rasheed,

Apologies for the delay in my response.
I have tested the updated DLL.
The reported issue is resolved.
However, it has introduced a new issue:
Pattern:

-          I opened the submitted sample chart in the Visual Editor

-          I clicked on every part of the chart XML tree to make sure the reported error no longer occurred

-          Without making any changed, I click Ok

-          I get this error:

-          System.ArgumentNullException: The value cannot be null.

Parameter name : s

Regards,
Louis

De : Mohamed Rasheed Gomaa (ITLec) [mailto:notifications@github.com]
Envoyé : 17 juin 2017 03:00
À : ITLec/ITLec.CRMChartGuy.XRMToolBox.AdvancedChartEditor <ITLec.CRMChartGuy.XRMToolBox.AdvancedChartEditor@noreply.github.com>
Cc : Lafil <lafil@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [ITLec/ITLec.CRMChartGuy.XRMToolBox.AdvancedChartEditor] Object reference not set to an instance of an object (#2)


Hello,

Kindly test the uploaded dll ["V2.0 - ITLecChartGuy.AdvancedChartEditor" in your onedrive folder"].
Please confirm that "This issue has been solved".

Thanks,
Rasheed

**Comment by ITLec** [comment]
Hello,

I am happy to hear that "The reported issue has been solved".

Related to the new issue, Can you tell me exactly which node cause this issue?

By the way I want to let you know that within the next coming days, There will a new version be released.

**Comment by ITLec** [comment]
Hi Lafil,

I would like to inform you that "The new release is available Now", So please check it and update the status for this issue.

**Comment by Lafil** [comment]
Issue resolved, thanks!
